# Generated by Django 3.0.3 on 2020-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200315_1910'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(null=True, to='books.Book'),
        ),
    ]
