# Generated by Django 3.0.3 on 2020-04-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
