# Generated by Django 3.0.3 on 2020-04-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200422_1925'),
        ('orders', '0006_auto_20200418_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_book', to='books.Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book', to='orders.Order')),
            ],
            options={
                'verbose_name': 'Book in order',
                'verbose_name_plural': 'Books in orders',
            },
        ),
    ]
