# Generated by Django 3.0.3 on 2020-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200422_1925'),
        ('orders', '0008_remove_order_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderBook', to='books.Book'),
        ),
    ]
