# Generated by Django 3.0.3 on 2020-04-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200422_1925'),
        ('orders', '0009_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Book'),
        ),
    ]
