# Generated by Django 3.0.3 on 2020-04-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200425_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('paid', 'Paid'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='registered', max_length=10),
        ),
    ]
