# Generated by Django 3.0.3 on 2020-05-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200503_1248'),
        ('books', '0010_auto_20200517_1621'),
        ('orders', '0013_auto_20200425_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='books.Book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
            },
        ),
    ]
