# Generated by Django 3.0.3 on 2020-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200315_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='buy_link',
        ),
        migrations.AddField(
            model_name='book',
            name='product_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
