# Generated by Django 3.0.3 on 2020-05-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200422_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='age_category',
        ),
        migrations.DeleteModel(
            name='AgeCategory',
        ),
    ]
