# Generated by Django 3.0.3 on 2020-05-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200507_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
        migrations.DeleteModel(
            name='BookLikeDislike',
        ),
    ]
