# Generated by Django 3.0.3 on 2020-05-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200510_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mark',
        ),
    ]
